export interface Product {
  id: number; name: string; slug: string; category: string;
  description: string; price: number; compareAt: number | null;
  rating: number; reviews: number; badge: string | null; badgeClass: string;
  imagePrompt: string; imageUrl: string;
}

export const PRODUCTS: Product[] = [
  // ═══ Monitor Stands (6) ═══
  { id:1, name:"Walnut Monitor Riser", slug:"walnut-monitor-riser", category:"Monitor Stand",
    description:"Solid FSC-certified American walnut. Hidden storage drawer. Cable cutout. Supports 50 lbs.", price:49.99, compareAt:69.99, rating:4.9, reviews:847, badge:"Bestseller", badgeClass:"bg-stone-900 text-white",
    imagePrompt:"professional product photo of solid walnut wood monitor stand riser on white desk, warm wood grain, hidden drawer, cable cutout, 8k e-commerce", imageUrl:"/images/product-1.jpg" },
  { id:2, name:"Aluminum Laptop Stand", slug:"aluminum-laptop-stand", category:"Monitor Stand",
    description:"Aerospace-grade matte aluminum. Adjustable height & angle. Anti-slip pads. 11-17\".", price:79.99, compareAt:99.99, rating:4.8, reviews:723, badge:"Popular", badgeClass:"bg-indigo-600 text-white",
    imagePrompt:"professional product photo of matte aluminum laptop stand on clean desk, MacBook at ergonomic height, sleek modern, 8k e-commerce", imageUrl:"/images/product-2.jpg" },
  { id:3, name:"Dual Monitor Arm — Black", slug:"dual-monitor-arm", category:"Monitor Stand",
    description:"Gas-spring for 13-32\" screens. Integrated cable channels. C-clamp & grommet mount.", price:129.99, compareAt:169.99, rating:4.8, reviews:456, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of matte black dual monitor arm holding two displays, floating effect, clean desk, 8k e-commerce", imageUrl:"/images/product-3.jpg" },
  { id:4, name:"Single Monitor Arm — White", slug:"single-monitor-arm-white", category:"Monitor Stand",
    description:"Gas-spring for 13-32\" screens. 360° rotation. USB pass-through. Clean white finish.", price:79.99, compareAt:null, rating:4.7, reviews:312, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of single white monitor arm on clean desk, one display floating, minimal, 8k e-commerce", imageUrl:"/images/product-4.jpg" },
  { id:21, name:"Bamboo Monitor Riser", slug:"bamboo-monitor-riser", category:"Monitor Stand",
    description:"Sustainable bamboo. 2-tier design with phone slot. Natural antibacterial surface. Lighter than walnut.", price:39.99, compareAt:null, rating:4.6, reviews:234, badge:"Eco", badgeClass:"bg-emerald-600 text-white",
    imagePrompt:"professional product photo of bamboo wood monitor stand riser on white desk, natural light bamboo grain, phone slot, 8k e-commerce", imageUrl:"/images/product-21.jpg" },
  { id:22, name:"Oak Monitor Riser — Light", slug:"oak-monitor-riser", category:"Monitor Stand",
    description:"European white oak. Extra-wide 55cm. Hidden drawer + cable cutout. Matches light wood desks.", price:54.99, compareAt:74.99, rating:4.8, reviews:189, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of light oak wood monitor stand riser on white desk, pale wood grain, minimalist Scandinavian, 8k e-commerce", imageUrl:"/images/product-22.jpg" },

  // ═══ Cable Management (5) ═══
  { id:5, name:"Magnetic Cable Organizer 8-Pack", slug:"magnetic-cable-organizer", category:"Cable Management",
    description:"Modular magnetic clips for desk & under-desk routing. No tools. Holds 8 cables each.", price:29.99, compareAt:null, rating:4.8, reviews:623, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of magnetic cable clips holding USB-C cables neatly on desk, organized, modern, 8k e-commerce", imageUrl:"/images/product-5.jpg" },
  { id:6, name:"Under-Desk Cable Tray — Steel", slug:"under-desk-cable-tray", category:"Cable Management",
    description:"Powder-coated steel. Clamp or screw mount. Ventilated. Fits power strips + bricks. 17\".", price:34.99, compareAt:44.99, rating:4.7, reviews:289, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of under desk metal cable tray mounted underneath desk, power strip inside, hidden cables, 8k e-commerce", imageUrl:"/images/product-6.jpg" },
  { id:7, name:"Velcro Cable Ties — 50-Pack", slug:"velcro-cable-ties", category:"Cable Management",
    description:"Reusable self-attaching. 6\" length. 50 ties. No adhesive residue. Black.", price:12.99, compareAt:null, rating:4.9, reviews:1102, badge:"Value", badgeClass:"bg-emerald-600 text-white",
    imagePrompt:"professional product photo of black velcro cable ties neatly bundled on white surface, minimal, 8k e-commerce", imageUrl:"/images/product-7.jpg" },
  { id:23, name:"Braided Cable Sleeve — 4 Pack", slug:"braided-cable-sleeve", category:"Cable Management",
    description:"Expandable PET braided sleeving. 1m each. Zipper closure. Fits 3-8 cables per sleeve.", price:16.99, compareAt:22.99, rating:4.5, reviews:178, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of black braided cable management sleeve covering multiple cables neatly on desk, organized, 8k e-commerce", imageUrl:"/images/product-23.jpg" },
  { id:24, name:"Desktop Cable Grommet — 2 Pack", slug:"desktop-cable-grommet", category:"Cable Management",
    description:"Aluminum finish. 60mm diameter. Pop-in installation. Brushes block dust. Fits standard desk holes.", price:12.99, compareAt:null, rating:4.6, reviews:312, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of aluminum round desk cable grommet installed in desk surface, cables passing through neatly, 8k e-commerce", imageUrl:"/images/product-24.jpg" },

  // ═══ Desk Mats (3) ═══
  { id:8, name:"Linen Desk Mat — Slate Blue", slug:"linen-desk-mat", category:"Desk Mat",
    description:"Premium linen + natural rubber. 90×40cm. Water-resistant. Slate blue.", price:34.99, compareAt:null, rating:4.7, reviews:512, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of slate blue linen desk mat on wooden desk, keyboard mouse on it, warm minimal, 8k e-commerce", imageUrl:"/images/product-8.jpg" },
  { id:9, name:"Linen Desk Mat — Warm Taupe", slug:"linen-desk-mat-taupe", category:"Desk Mat",
    description:"Same premium linen in warm taupe. Pairs with walnut desks. 90×40cm.", price:34.99, compareAt:null, rating:4.7, reviews:398, badge:"New", badgeClass:"bg-indigo-600 text-white",
    imagePrompt:"professional product photo of warm taupe linen desk mat on light wood desk, warm tones, keyboard on it, 8k e-commerce", imageUrl:"/images/product-9.jpg" },
  { id:25, name:"Felt Desk Mat — Charcoal", slug:"felt-desk-mat-charcoal", category:"Desk Mat",
    description:"3mm thick industrial wool felt. 90×43cm. Naturally water-repellent. Zero rubber smell.", price:39.99, compareAt:49.99, rating:4.8, reviews:267, badge:"Premium", badgeClass:"bg-stone-900 text-white",
    imagePrompt:"professional product photo of charcoal grey wool felt desk mat on wooden desk, premium texture, keyboard and notebook on it, 8k e-commerce", imageUrl:"/images/product-25.jpg" },

  // ═══ Lighting (4) ═══
  { id:10, name:"LED Monitor Light Bar", slug:"led-monitor-light-bar", category:"Lighting",
    description:"Asymmetric optical design. Zero screen glare. 3 color temps. Stepless dimming. USB-C.", price:49.99, compareAt:64.99, rating:4.6, reviews:389, badge:"Sale", badgeClass:"bg-red-600 text-white",
    imagePrompt:"professional product photo of sleek LED monitor light bar on display, warm glow on desk below, modern workspace, 8k e-commerce", imageUrl:"/images/product-10.jpg" },
  { id:11, name:"Architectural Desk Lamp — Black", slug:"desk-lamp-black", category:"Lighting",
    description:"Adjustable arm & head. Warm LED 3000K. Touch dimmer. USB-C charging port in base.", price:69.99, compareAt:89.99, rating:4.8, reviews:267, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of black architectural desk lamp with adjustable arm on minimal desk, warm light pool, 8k e-commerce", imageUrl:"/images/product-11.jpg" },
  { id:26, name:"RGB Monitor Backlight Strip", slug:"rgb-monitor-backlight", category:"Lighting",
    description:"USB-powered. 16.8M colors. App-controlled. Reduces eye strain. Fits 21-32\" monitors.", price:24.99, compareAt:null, rating:4.5, reviews:445, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of RGB LED strip behind a monitor on desk, colorful ambient backlight glow, gaming setup, 8k", imageUrl:"/images/product-26.jpg" },
  { id:27, name:"Wireless Charging Desk Lamp", slug:"wireless-charging-lamp", category:"Lighting",
    description:"15W fast wireless charger in base. 2700-6500K. Touch control. Eye-care diffuser.", price:89.99, compareAt:119.99, rating:4.7, reviews:198, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of modern desk lamp with built in wireless charging base, phone charging on it, minimal workspace, 8k e-commerce", imageUrl:"/images/product-27.jpg" },

  // ═══ Desk Organization (5) ═══
  { id:12, name:"Walnut Desk Shelf / Pegboard", slug:"walnut-desk-shelf", category:"Desk Organization",
    description:"Wall-mount or desk-lean. 3 shelves + peg holes. Solid walnut.", price:89.99, compareAt:119.99, rating:4.9, reviews:178, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of walnut wood desk shelf pegboard leaning on wall above desk, plants and stationery on shelves, 8k", imageUrl:"/images/product-12.jpg" },
  { id:13, name:"Ceramic Desk Planter — White", slug:"ceramic-desk-planter", category:"Desk Organization",
    description:"Matte white ceramic. Drainage hole + bamboo tray. 5\" diameter.", price:29.99, compareAt:null, rating:4.7, reviews:278, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of matte white ceramic desk planter with small green plant on minimal desk, bamboo tray, natural light, 8k e-commerce", imageUrl:"/images/product-13.jpg" },
  { id:14, name:"Pen & Tool Holder — Walnut", slug:"pen-tool-holder-walnut", category:"Desk Organization",
    description:"Solid walnut. 3 compartments. Felt-lined bottom. Fits pens, rulers, scissors.", price:39.99, compareAt:null, rating:4.6, reviews:156, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of walnut wood pen holder with pens and tools on clean desk, organized, warm wood, 8k e-commerce", imageUrl:"/images/product-14.jpg" },
  { id:28, name:"Drawer Organizer Set — 5 Piece", slug:"drawer-organizer-set", category:"Desk Organization",
    description:"Modular bamboo trays. 5 sizes. Felt base. Stackable. Fits IKEA and standard drawers.", price:24.99, compareAt:34.99, rating:4.6, reviews:234, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of bamboo drawer organizer set with stationery inside clean desk drawer, tidy, 8k e-commerce", imageUrl:"/images/product-28.jpg" },
  { id:29, name:"Magnetic Desktop Whiteboard", slug:"magnetic-whiteboard", category:"Desk Organization",
    description:"15×10\" tempered glass. 3 dry-erase markers + 2 magnets included. Wall or stand mount.", price:29.99, compareAt:null, rating:4.4, reviews:156, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of small glass magnetic whiteboard on desk with markers, notes written, modern workspace, 8k e-commerce", imageUrl:"/images/product-29.jpg" },

  // ═══ Comfort & Ergonomics (6) ═══
  { id:15, name:"Keyboard Wrist Rest — Walnut", slug:"keyboard-wrist-rest-walnut", category:"Comfort",
    description:"Solid walnut. Ergonomic 7° slope. Felt base. Full-size & TKL.", price:44.99, compareAt:59.99, rating:4.8, reviews:534, badge:"Popular", badgeClass:"bg-indigo-600 text-white",
    imagePrompt:"professional product photo of walnut wood keyboard wrist rest in front of keyboard on clean desk, ergonomic, warm wood, 8k e-commerce", imageUrl:"/images/product-15.jpg" },
  { id:16, name:"Memory Foam Footrest", slug:"memory-foam-footrest", category:"Comfort",
    description:"High-density memory foam. Washable velour cover. Non-slip base. 17×12×5\".", price:39.99, compareAt:null, rating:4.5, reviews:423, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of grey memory foam footrest under desk, ergonomic office setup, clean, 8k e-commerce", imageUrl:"/images/product-16.jpg" },
  { id:17, name:"Headphone Stand — Walnut", slug:"headphone-stand-walnut", category:"Comfort",
    description:"Solid walnut base + aluminum pole. Padded rest. Built-in cable management.", price:54.99, compareAt:74.99, rating:4.9, reviews:389, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of walnut wood headphone stand with black headphones hanging, elegant, on clean desk, 8k e-commerce", imageUrl:"/images/product-17.jpg" },
  { id:30, name:"Lumbar Support Cushion — Mesh", slug:"lumbar-support-cushion", category:"Comfort",
    description:"Breathable 3D mesh. Dual-density foam. Adjustable straps. Fits all office chairs.", price:49.99, compareAt:69.99, rating:4.6, reviews:567, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of grey mesh lumbar support cushion on black office chair, ergonomic, clean, 8k e-commerce", imageUrl:"/images/product-30.jpg" },
  { id:31, name:"Anti-Fatigue Standing Mat", slug:"anti-fatigue-mat", category:"Comfort",
    description:"High-density PU foam. Beveled edges. 83×51cm. For standing desk use.", price:79.99, compareAt:99.99, rating:4.7, reviews:312, badge:"Sale", badgeClass:"bg-red-600 text-white",
    imagePrompt:"professional product photo of black anti fatigue standing desk mat on floor in front of standing desk, ergonomic office, 8k e-commerce", imageUrl:"/images/product-31.jpg" },
  { id:32, name:"Wool Felt Keyboard Mat", slug:"wool-felt-keyboard-mat", category:"Comfort",
    description:"5mm thick German wool felt. Dampens typing sound. 80×30cm. Natural grey.", price:29.99, compareAt:null, rating:4.5, reviews:189, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of grey wool felt keyboard mat under keyboard on wooden desk, sound dampening texture, 8k e-commerce", imageUrl:"/images/product-32.jpg" },

  // ═══ Tech Accessories (5) ═══
  { id:18, name:"USB-C Hub — 7-in-1", slug:"usb-c-hub-7in1", category:"Tech",
    description:"HDMI 4K, 2×USB-A, USB-C PD 100W, SD/microSD, 3.5mm. Aluminum space grey.", price:49.99, compareAt:69.99, rating:4.6, reviews:672, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of sleek aluminum USB-C hub on white desk next to MacBook, minimal, 8k e-commerce", imageUrl:"/images/product-18.jpg" },
  { id:19, name:"Magnetic Webcam Cover — 3 Pack", slug:"magnetic-webcam-cover", category:"Tech",
    description:"Ultra-thin 0.7mm. Magnetic attachment. No adhesive. Fits all laptops & monitors.", price:9.99, compareAt:null, rating:4.8, reviews:891, badge:"Value", badgeClass:"bg-emerald-600 text-white",
    imagePrompt:"professional product photo of tiny magnetic webcam privacy cover on laptop screen bezel, close up detail, privacy, 8k e-commerce", imageUrl:"/images/product-19.jpg" },
  { id:33, name:"Wireless Charging Pad — Walnut", slug:"wireless-charging-pad-walnut", category:"Tech",
    description:"15W Qi2 fast charge. Solid walnut top. USB-C. For iPhone, AirPods, Android.", price:34.99, compareAt:null, rating:4.7, reviews:378, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of walnut wood wireless charging pad on desk with iPhone charging, warm wood, clean, 8k e-commerce", imageUrl:"/images/product-33.jpg" },
  { id:34, name:"Laptop Sleeve — Grey Felt", slug:"laptop-sleeve-felt", category:"Tech",
    description:"5mm wool felt. Magnetic closure. Fits 13-14\" and 15-16\" laptops. Water-resistant.", price:39.99, compareAt:null, rating:4.6, reviews:234, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of grey felt laptop sleeve on desk next to MacBook, premium wool texture, minimal, 8k e-commerce", imageUrl:"/images/product-34.jpg" },
  { id:35, name:"USB-C to HDMI Cable — 2m", slug:"usb-c-hdmi-cable", category:"Tech",
    description:"4K@60Hz. Braided nylon. Aluminum connectors. 2 meter length. Plug and play.", price:19.99, compareAt:29.99, rating:4.7, reviews:567, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of braided USB-C to HDMI cable neatly coiled on white desk, aluminum connectors, 8k e-commerce", imageUrl:"/images/product-35.jpg" },

  // ═══ Decor (4) ═══
  { id:36, name:"Mini Felt Notice Board — Grey", slug:"felt-notice-board", category:"Decor",
    description:"60×40cm German wool felt. Aluminum frame. Pin photos, notes, cards without damage.", price:24.99, compareAt:null, rating:4.5, reviews:189, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of grey felt notice board on wall above desk, photos and notes pinned, clean minimal, 8k", imageUrl:"/images/product-36.jpg" },
  { id:37, name:"Geometric Bookends — Steel", slug:"geometric-bookends", category:"Decor",
    description:"Powder-coated steel. Anti-slip base. Set of 2. Holds 15+ books. Modern sculptural look.", price:44.99, compareAt:59.99, rating:4.7, reviews:145, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of geometric metal bookends holding books on wooden desk shelf, modern sculptural, 8k e-commerce", imageUrl:"/images/product-37.jpg" },
  { id:38, name:"Minimal Desk Clock — Digital", slug:"desk-clock-digital", category:"Decor",
    description:"LED display. 3 brightness levels. Temperature + date. USB-C powered. Wood grain base.", price:34.99, compareAt:null, rating:4.6, reviews:267, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of minimal wood digital alarm clock on desk showing time, warm LED digits, clean workspace, 8k e-commerce", imageUrl:"/images/product-38.jpg" },
  { id:39, name:"Felt Coasters — 6 Pack", slug:"felt-coasters-6pack", category:"Decor",
    description:"5mm German wool felt. Heat-resistant. Non-slip. 6 colors. 10cm diameter.", price:19.99, compareAt:null, rating:4.8, reviews:312, badge:null, badgeClass:"",
    imagePrompt:"professional product photo of six colorful wool felt coasters stacked on wooden desk, clean warm aesthetic, 8k e-commerce", imageUrl:"/images/product-39.jpg" },

  // ═══ Bundles (2) ═══
  { id:20, name:"Complete Desk Makeover Kit", slug:"desk-makeover-kit", category:"Bundle",
    description:"Riser + Cable Organizer 8pk + Linen Mat + LED Light Bar. Save 25% vs individual.", price:129.99, compareAt:164.96, rating:4.9, reviews:312, badge:"Best Value", badgeClass:"bg-stone-900 text-white",
    imagePrompt:"professional product photo flat lay of desk accessories bundle, walnut stand, linen mat, cable clips, light bar, elegant, 8k e-commerce", imageUrl:"/images/product-20.jpg" },
  { id:40, name:"Ultimate Home Office Bundle", slug:"ultimate-home-office-bundle", category:"Bundle",
    description:"Makeover Kit + Lumbar Cushion + Footrest + Wireless Charger. Save 30%. 7 pieces total.", price:249.99, compareAt:359.93, rating:4.9, reviews:98, badge:"Ultimate", badgeClass:"bg-indigo-600 text-white",
    imagePrompt:"professional product photo flat lay of complete home office desk accessories bundle, riser mat lamp lumbar footrest charger, premium, 8k e-commerce", imageUrl:"/images/product-40.jpg" },
  { id:41, name:"Floating Monitor Shelf \u2014 Walnut", slug:"floating-monitor-shelf-walnut", category:"Monitor Stand",
    description:"Wall-mounted solid walnut shelf. Hidden bracket. Cable pass-through. 60cm wide.", price:59.99, compareAt:79.99, rating:4.7, reviews:156, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-41.jpg" },
  { id:42, name:"Dual Monitor Riser \u2014 Extra Wide", slug:"dual-monitor-riser-wide", category:"Monitor Stand",
    description:"100cm wide walnut riser. 2 drawers + center cutout. Supports 80 lbs.", price:79.99, compareAt:99.99, rating:4.6, reviews:134, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-42.jpg" },
  { id:43, name:"Adjustable Monitor Arm \u2014 Silver", slug:"adjustable-monitor-arm-silver", category:"Monitor Stand",
    description:"Polished aluminum. 360\u00b0 rotation. 13-32\". USB 3.0 hub. Gas spring.", price:99.99, compareAt:null, rating:4.5, reviews:98, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-43.jpg" },
  { id:44, name:"Kids Monitor Stand \u2014 White Oak", slug:"kids-monitor-stand-oak", category:"Monitor Stand",
    description:"Child-height solid oak riser. Rounded corners. Cable management.", price:44.99, compareAt:59.99, rating:4.8, reviews:67, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-44.jpg" },
  { id:45, name:"Cable Raceway Kit \u2014 6 Pack", slug:"cable-raceway-kit-6pack", category:"Cable Management",
    description:"Adhesive PVC channels. Paintable white. 40cm each. Includes connectors.", price:19.99, compareAt:null, rating:4.5, reviews:223, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-45.jpg" },
  { id:46, name:"Power Strip Holder \u2014 Under Desk", slug:"power-strip-holder-under-desk", category:"Cable Management",
    description:"Clamp-mount steel bracket. Fits standard power strips. No drilling.", price:14.99, compareAt:null, rating:4.6, reviews:189, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-46.jpg" },
  { id:47, name:"USB Cable Organizer Box \u2014 Bamboo", slug:"usb-cable-organizer-box", category:"Cable Management",
    description:"Bamboo lid + ABS body. Hides power strip + cables. Ventilated.", price:24.99, compareAt:34.99, rating:4.4, reviews:145, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-47.jpg" },
  { id:48, name:"Leather Desk Mat \u2014 Brown", slug:"leather-desk-mat-brown", category:"Desk Mat",
    description:"Genuine top-grain leather. Suede underside. 90\u00d743cm. Ages beautifully.", price:59.99, compareAt:79.99, rating:4.8, reviews:178, badge:"Premium", badgeClass:"bg-stone-900 text-white",
    imagePrompt:"", imageUrl:"/images/product-48.jpg" },
  { id:49, name:"Cork Desk Mat \u2014 Natural", slug:"cork-desk-mat-natural", category:"Desk Mat",
    description:"Sustainable Portuguese cork. 90\u00d743cm. Antimicrobial. Lightweight.", price:29.99, compareAt:null, rating:4.5, reviews:98, badge:"Eco", badgeClass:"bg-emerald-600 text-white",
    imagePrompt:"", imageUrl:"/images/product-49.jpg" },
  { id:50, name:"Extended Desk Mat \u2014 XXL Black", slug:"extended-desk-mat-xxl", category:"Desk Mat",
    description:"120\u00d760cm. Micro-woven fabric. Waterproof. Stitched edges.", price:49.99, compareAt:64.99, rating:4.7, reviews:234, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-50.jpg" },
  { id:51, name:"Screen Bar Pro \u2014 Dual Light", slug:"screen-bar-pro-dual-light", category:"Lighting",
    description:"Front + back dual lighting. Auto-dimming sensor. Wireless remote.", price:69.99, compareAt:89.99, rating:4.7, reviews:167, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-51.jpg" },
  { id:52, name:"Desk Lamp \u2014 Walnut & Brass", slug:"desk-lamp-walnut-brass", category:"Lighting",
    description:"Walnut veneer + brass stem. Dimmable LED. Mid-century modern design.", price:79.99, compareAt:null, rating:4.9, reviews:89, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-52.jpg" },
  { id:53, name:"Under-Shelf LED Strip \u2014 3 Pack", slug:"under-shelf-led-strip-3pack", category:"Lighting",
    description:"Motion sensor. Rechargeable. Magnetic mount. 30cm each. Warm white.", price:34.99, compareAt:null, rating:4.6, reviews:312, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-53.jpg" },
  { id:54, name:"Ring Light \u2014 Video Call Kit", slug:"ring-light-video-call-kit", category:"Lighting",
    description:"10\" diameter. 3 color modes + 10 brightness. Tripod + phone holder.", price:39.99, compareAt:54.99, rating:4.5, reviews:445, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-54.jpg" },
  { id:55, name:"Stackable Paper Tray \u2014 Walnut", slug:"stackable-paper-tray-walnut", category:"Desk Organization",
    description:"Solid walnut. 3-tier modular. Felt-lined. Fits A4/Letter.", price:49.99, compareAt:null, rating:4.6, reviews:134, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-55.jpg" },
  { id:56, name:"Sticky Note Holder \u2014 Walnut", slug:"sticky-note-holder-walnut", category:"Desk Organization",
    description:"Solid walnut base. Holds 3\u00d73\" notes. Pen slot. Weighted.", price:19.99, compareAt:null, rating:4.7, reviews:198, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-56.jpg" },
  { id:57, name:"Trash Can \u2014 Matte Black", slug:"trash-can-matte-black", category:"Desk Organization",
    description:"6L capacity. Powder-coated steel. Soft-close lid. Removable bucket.", price:34.99, compareAt:null, rating:4.5, reviews:167, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-57.jpg" },
  { id:58, name:"Letter Sorter \u2014 Bamboo", slug:"letter-sorter-bamboo", category:"Desk Organization",
    description:"5 compartments. Vertical design. Fits envelopes and mail.", price:29.99, compareAt:39.99, rating:4.4, reviews:123, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-58.jpg" },
  { id:59, name:"Rolling Desk Drawer \u2014 White", slug:"rolling-desk-drawer-white", category:"Desk Organization",
    description:"3 lockable drawers on casters. Fits under desks. Metal + MDF.", price:69.99, compareAt:89.99, rating:4.6, reviews:98, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-59.jpg" },
  { id:60, name:"Gel Wrist Rest \u2014 Black", slug:"gel-wrist-rest-black", category:"Comfort",
    description:"Cooling gel + memory foam. Lycra cover. Non-slip. Full-size.", price:24.99, compareAt:null, rating:4.6, reviews:312, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-60.jpg" },
  { id:61, name:"Seat Cushion \u2014 Memory Foam", slug:"seat-cushion-memory-foam", category:"Comfort",
    description:"High-density foam. Washable 3D mesh cover. 45\u00d740\u00d78cm.", price:44.99, compareAt:59.99, rating:4.5, reviews:278, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-61.jpg" },
  { id:62, name:"Monitor Riser \u2014 3-Level Adjustable", slug:"monitor-riser-adjustable-3level", category:"Comfort",
    description:"3 heights (10/13/16cm). Steel + wood top. Ergonomic eye level.", price:44.99, compareAt:null, rating:4.7, reviews:189, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-62.jpg" },
  { id:63, name:"Standing Desk Balance Board", slug:"standing-desk-balance-board", category:"Comfort",
    description:"Curved rocker. Anti-slip. Core engagement while standing. 66\u00d733cm.", price:49.99, compareAt:null, rating:4.6, reviews:145, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-63.jpg" },
  { id:64, name:"USB-C Hub \u2014 12-in-1 Pro", slug:"usb-c-hub-12in1-pro", category:"Tech",
    description:"Dual HDMI, 3\u00d7USB-A, 2\u00d7USB-C, SD, Ethernet, Audio. 100W PD.", price:79.99, compareAt:99.99, rating:4.7, reviews:234, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-64.jpg" },
  { id:65, name:"Vertical Laptop Stand \u2014 Dual", slug:"vertical-laptop-stand-dual", category:"Tech",
    description:"Holds 2 laptops. Adjustable width. Aluminum. Non-slip base.", price:39.99, compareAt:null, rating:4.5, reviews:178, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-65.jpg" },
  { id:66, name:"Screen Cleaning Kit", slug:"screen-cleaning-kit", category:"Tech",
    description:"Microfiber cloth + plant-based spray. Anti-static. Safe for all screens.", price:14.99, compareAt:null, rating:4.8, reviews:345, badge:"Value", badgeClass:"bg-emerald-600 text-white",
    imagePrompt:"", imageUrl:"/images/product-66.jpg" },
  { id:67, name:"Monitor Privacy Filter \u2014 24\"", slug:"monitor-privacy-filter-24", category:"Tech",
    description:"Anti-glare + privacy. Magnetic attachment. 16:9. Blocks side views.", price:39.99, compareAt:54.99, rating:4.4, reviews:156, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-67.jpg" },
  { id:68, name:"Air Duster \u2014 Rechargeable", slug:"air-duster-rechargeable", category:"Tech",
    description:"Brushless motor. 50000 RPM. USB-C recharge. For keyboards + electronics.", price:29.99, compareAt:null, rating:4.6, reviews:278, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-68.jpg" },
  { id:69, name:"Mini Succulent Set \u2014 3 Pack", slug:"mini-succulent-set-3pack", category:"Decor",
    description:"Real live succulents in concrete pots. Low maintenance. Desk-friendly.", price:24.99, compareAt:null, rating:4.7, reviews:234, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-69.jpg" },
  { id:70, name:"LED Neon Sign \u2014 Focus", slug:"led-neon-sign-focus", category:"Decor",
    description:"\"FOCUS\" in warm white LED. Dimmable. USB powered. 40cm wide.", price:34.99, compareAt:44.99, rating:4.8, reviews:167, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-70.jpg" },
  { id:71, name:"Hourglass \u2014 30 Minute", slug:"hourglass-30-minute", category:"Decor",
    description:"Hand-blown glass. Black sand. Walnut base. Desk timer + decor.", price:44.99, compareAt:null, rating:4.9, reviews:89, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-71.jpg" },
  { id:72, name:"Magnetic Photo Frame \u2014 3 Pack", slug:"magnetic-photo-frame-3pack", category:"Decor",
    description:"Acrylic magnetic frames. 10\u00d715cm. Wall-mount or desk-stand.", price:19.99, compareAt:null, rating:4.5, reviews:123, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-72.jpg" },
  { id:73, name:"Cable Management Kit", slug:"cable-management-kit", category:"Bundle",
    description:"Magnetic Clips 8pk + Cable Tray + Sleeves 4pk + Velcro 50pk. Save 20%.", price:59.99, compareAt:74.96, rating:4.8, reviews:156, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-73.jpg" },
  { id:74, name:"Ergonomic Starter Kit", slug:"ergonomic-starter-kit", category:"Bundle",
    description:"Wrist Rest + Lumbar Cushion + Footrest + Seat Cushion. Save 25%.", price:119.99, compareAt:159.96, rating:4.7, reviews:134, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-74.jpg" },
  { id:75, name:"Desk Aesthetics Set", slug:"desk-aesthetics-set", category:"Bundle",
    description:"Riser + LED Bar + Mat + Clock + Planter. Save 20%.", price:149.99, compareAt:188.95, rating:4.9, reviews:78, badge:null, badgeClass:"",
    imagePrompt:"", imageUrl:"/images/product-75.jpg" },
];

export const SLIDES = [
  { tag:"40+ Products", title:"Everything Your Desk Needs", description:"From monitor stands to cable management, lighting to comfort — one store, complete workspace.", cta:"Shop All Products", href:"/collections/monitor-stands",
    imagePrompt:"beautiful warm minimal desk setup with every desk accessory, monitor stand, mat, lamp, plants, organized, natural light, 8k lifestyle" },
  { tag:"Most Popular", title:"Zero Clutter. Full Focus.", description:"Magnetic cable management in 60 seconds. No tools, no drilling.", cta:"Shop Cable Management", href:"/products/magnetic-cable-organizer",
    imagePrompt:"clean desk with invisible cable management, no visible wires, minimal modern workspace, before after, 8k lifestyle" },
  { tag:"Bundle & Save", title:"Save 30% on the Ultimate Bundle", description:"7 pieces: riser, mat, light, cable kit, lumbar support, footrest, charger.", cta:"Shop Ultimate Bundle", href:"/products/ultimate-home-office-bundle",
    imagePrompt:"complete home office desk setup with all accessories, ergonomic chair, monitor arm, plants, warm lighting, perfect workspace, 8k" },
];

export const CATEGORIES = [
  { name:"Monitor Stands", slug:"monitor-stands", imageKey:"collection-protection" },
  { name:"Cable Management", slug:"cable-management", imageKey:"collection-love" },
  { name:"Desk Mats", slug:"desk-mats", imageKey:"collection-anxiety" },
  { name:"Lighting", slug:"lighting", imageKey:"collection-wealth" },
  { name:"Comfort", slug:"comfort", imageKey:"collection-comfort" },
  { name:"Tech", slug:"tech", imageKey:"collection-tech" },
  { name:"Desk Organization", slug:"desk-organization", imageKey:"collection-organization" },
  { name:"Decor", slug:"decor", imageKey:"collection-decor" },
];

export const categoryMap: Record<string, string> = {
  "monitor-stands":"Monitor Stand", "cable-management":"Cable Management",
  "desk-mats":"Desk Mat", "lighting":"Lighting", "comfort":"Comfort",
  "tech":"Tech", "desk-organization":"Desk Organization", "decor":"Decor",
};
