import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service — DeskVibe" };

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12 prose prose-stone prose-sm">
      <h1>Terms of Service</h1>
      <p>Last updated: June 16, 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using DeskVibe (deskvibe.com), you agree to be bound by these Terms of Service. If you do not agree, please do not use our website.</p>

      <h2>2. Products & Pricing</h2>
      <p>All prices are listed in US Dollars (USD) and are subject to change without notice. We reserve the right to modify or discontinue any product at any time. Product images are generated by AI for illustration purposes — actual products may vary slightly in appearance.</p>

      <h2>3. Orders & Payment</h2>
      <p>By placing an order, you agree to pay the total amount shown at checkout including any applicable shipping fees. Payment is processed through PayPal. Your order is confirmed once payment is received and verified.</p>

      <h2>4. Shipping</h2>
      <p>Orders are processed within 1-3 business days. Standard international shipping takes 7-12 business days. Free shipping is available on orders over $75. Tracking information is provided for all orders. DeskVibe is not responsible for customs duties or import taxes that may apply.</p>

      <h2>5. Returns & Refunds</h2>
      <p>We offer a 30-day return policy. Products must be returned in original packaging and condition. Return shipping costs are the responsibility of the buyer unless the product arrived damaged or defective. Refunds are processed within 3-5 business days of receiving the returned item.</p>

      <h2>6. Intellectual Property</h2>
      <p>All content on this website including images, text, logos, and designs is the property of DeskVibe and protected by copyright laws.</p>

      <h2>7. Limitation of Liability</h2>
      <p>DeskVibe shall not be liable for any indirect, incidental, or consequential damages arising from the use of our products or website. Our maximum liability is limited to the purchase price of the product in question.</p>

      <h2>8. Contact</h2>
      <p>support@deskvibe.com</p>
    </div>
  );
}
